---
title: "Revenue_Prediction"
author: "David Palazzo"
date: "6/7/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glmnet)
#install.packages("xgboost")
library(xgboost)
library(dplyr) 
library(naniar)
library(jsonlite)
```

```{r}
# Load data
test_data = read.csv('test_data.csv')
train_data = read.csv('train_data.csv')
# drop the first and third column of each dataframe
train_data <- train_data[-c(1,3)]
test_data <- test_data[-c(1,3)]
```

```{r}
# Split into X,y
y_train <- train_data$totals.transactionRevenue
X_train <- train_data[, !(colnames(train_data) %in% c('totals.transactionRevenue'))]
y_test <- test_data$totals.transactionRevenue
X_test <- test_data[, !(colnames(test_data) %in% c('totals.transactionRevenue'))]
```

```{r}
is_na_val <- function(x) x %in% c("not available in demo dataset", "(not provided)",
                                  "(not set)", "<NA>", "unknown.unknown",  "(none)")

# change missing values to NA
X_train <- X_train %>% mutate_all(funs(ifelse(is_na_val(.), NA, .)))
X_test <- X_test %>% mutate_all(funs(ifelse(is_na_val(.), NA, .)))

# only show missing values greater than zero
missing <- X_train[,X_train %>% summarize_all(funs(sum(is.na(.))/length(.))) > 0.01]
gg_miss_var(missing, show_pct=TRUE)


```

```{r}
#change missing values to 0
X_train$totals.totalTransactionRevenue[is.na(X_train$totals.totalTransactionRevenue)] <- 0
X_train$totals.transactions[is.na(X_train$totals.transactions)] <- 0
X_test$totals.totalTransactionRevenue[is.na(X_test$totals.totalTransactionRevenue)] <- 0
X_test$totals.transactions[is.na(X_test$totals.transactions)] <- 0

#drop missing columns
drop_names <- c("trafficSource.adwordsClickInfo.criteriaParameters","geoNetwork.networkLocation","geoNetwork.longitude","geoNetwork.latitude","geoNetwork.cityId","device.screenResolution","device.screenColors","device.operatingSystemVersion", "device.mobileInputSelector","device.mobileDeviceModel","device.mobileDeviceMarketingName","device.mobileDeviceInfo","device.mobileDeviceBranding","device.language","device.flashVersion","device.browserVersion","device.browserSize")

X_train <- X_train[,!(names(X_train) %in% drop_names)]
X_test <- X_test[,!(names(X_test) %in% drop_names)]
```

```{r}
# get index for train/validate split before dropping date column
split_idx <- X_train$date < 20160808

```


```{r}
# Drop ID columns and total Rev
X_train %<>% 
  select(-date, -fullVisitorId, -visitId, -visitStartTime, -totals.totalTransactionRevenue, -totals.transactions) %>% 
  mutate_if(is.character, funs(factor(.) %>% as.integer))
X_test  %<>% 
  select(-date, -fullVisitorId, -visitId, -visitStartTime, -totals.totalTransactionRevenue,-totals.transactions) %>% 
  mutate_if(is.character, funs(factor(.) %>% as.integer))
# Replace NAs with 0 for y variable revenue
y_train[is.na(y_train)]<- 0
y_test[is.na(y_test)] <- 0
```


For EDA purposes we will transform y variable to actual dollar value. Our data has transaction revenue multiplied by $10^6$. 

```{r}
train_y_EDA<- y_train/1000000
summary(train_y_EDA)
# Drop 0 instances
train_y_EDA<- train_y_EDA[!(train_y_EDA==0)]
# drop values over 1000
train_y_EDA<- train_y_EDA[!(train_y_EDA>1000)]
g <- ggplot(data = data_frame(train_y_EDA),aes(train_y_EDA)) + 
geom_histogram(binwidth = 10,color='black', fill='blue') + labs(title = "Histogram of Transaction Revenue") + labs(x=" Transaction Revenue in Dollars") 
g
```

Let's take a look at the density plot of the natural log of Transaction revenue, which is the y value that we will predict.

```{r}
train_y_EDA<- log(train_y_EDA)
g <- ggplot(data = data_frame(train_y_EDA),aes(x=train_y_EDA, y= ..density..)) + 
geom_histogram(binwidth = .6, color='black',fill='blue') + labs(title = "Density of Log Transaction Revenue") + labs(x=" Log Transaction Revenue") 
g
```

```{r}
#y_train <- log1p(y_train$totals.transactionRevenue)
#y_test <- log1p(y_test$totals.transactionRevenue)

dtrain <- xgb.DMatrix(data = data.matrix(X_train),label = data.matrix(y_train) )
dtest <- xgb.DMatrix(data = data.matrix(X_test),label=data.matrix(y_test))
```

```{r}
xgb <- xgb.train(data = dtrain, nrounds = 50, nfold = 5)
y_pred <- predict(xgb, dtest)

```


```{r}
X_names <- names(X_train)
importance_matrix <- xgb.importance(X_names, model = xgb)
xgb.plot.importance(importance_matrix)
```

```{r}
test <- chisq.test(X_train$totals.pageviews, y_train)
print(test)

```


```{r}
# create train, validation and test sets

Dtrain <- xgb.DMatrix(data = data.matrix(X_train[split_idx, ]), label = data.matrix(y_train[split_idx, ]))
Dval <- xgb.DMatrix(data = data.matrix(X_train[!split_idx, ]), label = data.matrix(y_train[!split_idx, ]))

xgb.train(data=Dtrain, nrounds= 50, watchlist= list(val=Dval))

```
